### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by jasonroelofs** [countries/countries#499] opened 2018-02-16 15:59 UTC
I believe this gem has a race condition issue regarding the country data cache.

We've started randomly seeing the following exception in our app that happens with no immediately obvious reason.

```
NoMethodError: undefined method `[]' for nil:NilClass 
[GEM_ROOT]/gems/countries-2.1.2/lib/countries/country.rb:87:in `translation'
```

In master the line in question is https://github.com/hexorx/countries/blob/master/lib/countries/country.rb#L91

Looking through the code throwing this exception, I'm noticing that `data` is a regularly-reloaded in-memory cache of country information. As we are running `puma` with multiple workers and multiple threads, it's starting to look like a potential race condition in reloading `data`, leading to empty keys and nil values.

I haven't had a ton of time to see if I can explicitly reproduce this issue myself, but wanted to bring it up and see if anyone has hit this, has thought about thread safety of this library, or if I'm missing something else entirely.

Thanks.

**Comment by rposborne** [comment] 2018-02-16 16:07
@jasonroelofs  Hmmm, I'll try to dig in on this. But the statement "regularly-reloaded" seems to trip me up.   Once countries boots we try to NEVER reload data as this drives memory thrash, and was a major issue for us earlier in the gems history.  

If your app is manipulating i18n available locales, during runtime, I could see a possibility here,  but I am not sure.

**Comment by jasonroelofs** [comment] 2018-02-16 17:31
We shouldn't be but thanks for the pointer.  I'll do some more digging to see if I can track down why this data would suddenly disappear.

**Comment by rposborne** [comment] 2018-02-22 14:58
@jasonroelofs Any progress on tracking down your issues?  Would love to know if we need to dive on this.

**Comment by jasonroelofs** [comment] 2018-02-22 19:57
I'm sorry I have not. I will try to get something soon.

**Comment by jasonroelofs** [comment] 2018-03-05 18:22
@rposborne It hasn't been an easy thing to forcibly trigger, as you can imagine. We downgraded our app back to the previous version, 2.0.6, and we have not seen a single instance of this problem. I've dived through the history of the app since that release for anything related to countries and data caching and have ended up on this commit: https://github.com/hexorx/countries/commit/3733179333c924babd2f8a166d3a777f0b81fd2f

I'm wondering if somehow Puma workers with multiple threads are somehow interfering with `cache_dir` (and we don't explicitly set that in our app so it *should* be default). Next step is probably taking a fork of the library with this commit reverted and seeing if the problem persists. Do you see anything suspicious here?

**Comment by jasonroelofs** [comment] 2018-03-23 13:13
An update, we've started seeing the problem even for version 2.0.6. For now I'm forking the gem and adding some protection hooks around `Country#translate` to see if I can safely catch the error next time it happens.

https://github.com/jasonroelofs/countries/tree/debugging

**Comment by jasonroelofs** [comment] 2018-05-18 13:46
Still randomly hitting this but no so providing an update.

Best I can guess right now is that `ISO3166::Data#locales_to_load` is somehow returning empty when `@@cache` isn't fully loaded.

**Comment by egze** [comment] 2018-07-04 15:41
We also got this exception today. `countries (2.1.4)`

**Comment by cgunther** [comment] 2018-07-05 16:07
I'm hitting this as well (v2.1.4), but in background jobs via Sidekiq, which is also multi-threaded. I've noticed it twice now after a reboot of the server, so the Sidekiq process hasn't loaded/cached any data yet and the error happens once multiple jobs are enqueued/run simultaneously that all need to load/cache the data. Even with Sidekiq's auto retries, the error still persists when the job is tried again.

As a simple reproduction, this shows the error about 70% of the time for me:
```ruby
require 'countries'

(0...10).map do
  Thread.new do
    ISO3166::Country.new('US').translation
  end
end.map(&:join)
```

If I instantiate a new country (even a different country) before creating the threads, the error goes away.

I'll see if I can dig a little deeper in the coming days.

**Comment by rposborne** [comment] 2018-07-05 16:11
@cgunther thanks for this,   If anyone has ideas on the solve for this I am all ears.

@kasparsj we may need to rollback that commit unless we have a way to solve the dynamic cache dir.

**Comment by egze** [comment] 2018-07-12 09:06
I'm going to try and put this in sidekiq config:
```ruby
Sidekiq.configure_server do |config|
  config.on(:startup) do
      ISO3166::Data.load_data!
  end
end
```
I hope this loads the data before sidekiq creates threads. I will report back after we deploy a couple of times.

But in general, right now the gem is not thread-safe. Using class variables for state is asking for trouble. I have a feeling a larger refactoring is needed to solve this.

**Comment by egze** [comment] 2018-07-19 09:06
So far so good. Haven't noticed any exception since my fix.

**Comment by jasonroelofs** [comment] 2018-09-11 13:48
I'm convinced now that it is a thread safety issue. We just hit this again right after Heroku did its daily dyno restart. Our dyno setup is one Puma worker running 5 threads, and with the right set of traffic, those threads will hit `ISO3166::Data#load_cache` at the same time, causing conflicts of how `@@cache` gets loaded into memory. I'm going to do something similar to @egze's fix in Puma's `on_worker_boot` and see where things go from there.

**Comment by silviorelli** [comment] 2019-09-18 08:38
Hi all,
I'm hitting this issue, with Puma on Heroku, Ruby 2.6.4 & Rails 5.2.3.

It completely hangs the application and requires a dyno restart to be solved.
This is a rather serious issue due to the unpredictable behaviour, it happens more or less once in a week, at any time.

I agree that race conditions are occurring due to the use of @@ class variables in countries/lib/countries/data.rb.

**Comment by silviorelli** [comment] 2019-09-18 09:38
As a workaround I followed @egze's and @jasonroelofs' suggestions, adding this block to puma.rb

`preload_app!
on_worker_boot do
  ISO3166::Data.load_data!
end`

**Comment by juanmanuelramallo** [comment] 2019-09-18 14:57
> As a workaround I followed @egze's and @jasonroelofs' suggestions, adding this block to puma.rb
> 
> ```
> preload_app!
> on_worker_boot do
>   ISO3166::Data.load_data!
> end
> ```
> 
> ref: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#preload-app

Hey @silviorelli, it that solution working for you?

**Comment by silviorelli** [comment] 2019-09-19 11:38
So far so good.

**Comment by jefffairson** [comment] 2019-10-18 15:37
Hello @silviorelli 
Did you experienced any errors yet ?
We have this issue for sometimes on our app with the same type of configuration as yours, we'll try to use your solution.

**Comment by silviorelli** [comment] 2019-10-19 14:57
@jefffairson no more errors since september.

**Comment by kephas** [comment] 2019-10-21 10:04
Also that solution didn't seem to work for us. We put the `on_worker_boot` and still had a few such errors in the following minutes.

**Comment by kephas** [comment] 2019-10-25 13:47
Today, we seemed to have this issue, but it happened several hours after a new container was fired up for our application (we're on [Scalingo](https://scalingo.com/), a Heroku clone).

So it's probably not a race condition at application start. I'm not (yet) sure if our code may modify the data and trigger reloads; as was hinted earlier might be one cause of this bug.

**Comment by hammerdr** [comment] 2019-12-17 19:24
Just to add to the chorus, we are experiencing this in Sidekiq with threads, too. Attempting the workaround for now and I may take a stab at making this lib thread safe later today.

**Comment by pmor** [comment] 2022-08-02 15:59
This looks like it's no longer an issue, so I'm closing it

**Closed by pmor** 2022-08-02 15:59 UTC
